stages:
    - upload

upload:
    stage: upload
    only:
        - master
    except:
        - tag
    script:
        - git checkout master
        - git pull origin master
        - git remote add github https://$GITHUB_USER:$GITHUB_TOKEN@github.com/comarch-cybersecurity/tproecc_node_tutorial.git
        - git push github master
        - git remote remove github
    tags:
        - node.js
